concurrent = 12
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "creon"
  limit = 5
  request_concurrency = 5
  url = "https://gitlab.nrao.edu/"
  id = 47
  # Token removed for security
  #token = ""
  token_obtained_at = 2023-03-17T16:06:19Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    host = "unix:///run/docker.sock"
    tls_verify = false
    image = "quay.io/podman/stable"
    privileged = false
    disable_entrypoint_overwrite = false
    cap_add = ["NET_ADMIN"]
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "bridge"
    pull_policy = ["if-not-present"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "creon_questa"
  limit = 1
  request_concurrency = 1
  url = "https://gitlab.nrao.edu/"
  id = 48
  # Token removed for Security
  #token = ""
  token_obtained_at = 2023-03-19T11:08:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    host = "unix:///run/docker.sock"
    tls_verify = false
    image = "questasim:2023.1"
    privileged = false
    disable_entrypoint_overwrite = false
    cap_add = ["NET_ADMIN"]
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "bridge"
    pull_policy = ["never"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "creon_vivado_vol"
  url = "https://gitlab.nrao.edu"
  id = 60
  limit = 5
  request_concurrency = 5
  # token removed for security
  #token = ""
  token_obtained_at = 2023-11-30T01:16:38Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    pull_policy = ["never"]
    image = "vivado_vol:2023.2"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    # Xilinx tools are expected at
    # /tools/Xilinx/Vivado/2023.2/settings64.sh
    # in prep for this runner to run other tools we share the entire Tools volume
    volumes = ["/cache", "/tools:/tools"]
    shm_size = 0
    network_mtu = 0
