FROM almalinux:8
RUN dnf update -y \
    && dnf install -y \
        gcc \
        yum-utils \
        python3 \
        libnsl \
        glibc-all-langpacks \
        unzip \
        wget \
	    unzip \
        net-tools \
        git \
        tbb \
        python3 \
        python3-pip \
	    libX11 \
        libXext \
        libXft \
        libSM \
    && dnf config-manager --set-enabled powertools \
    && dnf install -y libXdmcp-devel qt5-devel\
    && dnf clean all

RUN python3 -m pip install pytest --progress-bar off
RUN python3 -m pip install numpy --progress-bar off
#RUN python3 -m pip install vunit-hdl --progress-bar off
RUN git clone --recurse-submodules https://github.com/VUnit/vunit.git
RUN cd vunit && \
    python3 setup.py install

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8   

ENV QUARTUS_PATH=/tools/quartus/2023.3
ENV QUARTUS_ROOTDIR=${QUARTUS_PATH}/quartus
ENV SOPC_KIT_NIOS2=${QUARTUS_PATH}/nios2eds
ENV PATH=${QUARTUS_ROOTDIR}/bin/:${QUARTUS_ROOTDIR}/linux64/gnu/:${QUARTUS_ROOTDIR}/sopc_builder/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PATH=${SOPC_KIT_NIOS2}/:${SOPC_KIT_NIOS2}/bin/:${SOPC_KIT_NIOS2}/bin/gnu/H-x86_64-pc-linux-gnu/bin/:${SOPC_KIT_NIOS2}/sdk2/bin/:$PATH
ENV INTELFPGAOCLSDKROOT="${QUARTUS_PATH}/hld"
ENV QSYS_ROOTDIR="${QUARTUS_PATH}/qsys/bin"
# Note: This docker will expect /tools to be mounted as a volume from the host
# /tools/quartus/2023.2/quartus/bin  must have the Quartus binaries installed.
