FROM raetro/quartus:base
ENV LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4
ENV QUARTUS_PATH=/tools/quartus/2023.3
ENV SOPC_KIT_NIOS2=${QUARTUS_PATH}/nios2eds
ENV PATH=${QUARTUS_ROOTDIR}/bin/:${QUARTUS_ROOTDIR}/linux64/gnu/:${QUARTUS_ROOTDIR}/sopc_builder/bin/:$PATH
ENV PATH=${SOPC_KIT_NIOS2}/:${SOPC_KIT_NIOS2}/bin/:${SOPC_KIT_NIOS2}/bin/gnu/H-x86_64-pc-linux-gnu/bin/:${SOPC_KIT_NIOS2}/sdk2/bin/:$PATH
ENV INTELFPGAOCLSDKROOT="${QUARTUS_PATH}/hld"
ENV QSYS_ROOTDIR="${QUARTUS_PATH}/qsys/bin"
# Note: This docker will expect /tools to be mounted as a volume from the host
# /tools/quartus/2023.2/quartus/bin  must have the Quartus binaries installed.