version: "3"
services:
  windows:
    # based on dockurr/windows
    image: dockurr/windows
    container_name: windows
    volumes:
      - /export/data/home/gitlab-runner/win_docker:/storage
    devices:
      - /dev/kvm
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8006:8006
      - 127.0.0.1:33895:3389/tcp
      - 127.0.0.1:33895:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      ARGUMENTS: "-device usb-host,hostbus=1,hostaddr=16 -device usb-host,hostbus=1,hostaddr=7 -device usb-host,hostbus=1,hostaddr=14 -device usb-host,hostbus=1,hostaddr=13 -device usb-host,hostbus=1,hostaddr=9"
