# this expects the vivado.tar.gz to bind mounted during the build into /tmp/vivado.tar.gz
# podman build -t vivado:2022.2 --squash-all --volume /export/data_1/gitlab-runner/docker_builds/vivado/vivado.tar.gz:/tmp/vivado.tar.gz .
FROM ubuntu:22.04
ENV XLNX_INSTALL_LOCATION=/tools/Xilinx
ENV DEBIAN_FRONTEND=noninteractive  
RUN apt-get update
RUN dpkg --add-architecture i386 
RUN apt-get update 
RUN apt-get upgrade -y
# petalinux base dependencies
RUN apt-get install -y \
		tofrodos \
		iproute2 \
		gawk \
		xvfb \
		git \
		make \
		net-tools \
		libncurses5-dev \
		update-inetd \
		tftpd \
		zlib1g-dev:i386 \
		libssl-dev \
		flex \
		bison \
		libselinux1 \
		gnupg \
		wget \
		diffstat \
		chrpath \
		socat \
		xterm \
		autoconf \
		libtool \
		libtool-bin \
		libtinfo5 \
		sudo \
		tar \
		unzip \
		texinfo \
		zlib1g-dev \
		gcc-multilib \
		build-essential \
		libsdl1.2-dev \
		libglib2.0-dev \
		screen \
		pax \
		gzip \
		python3-gi \
		less \
		lsb-release \
		fakeroot \
		libgtk2.0-0 \
		libgtk2.0-dev \
		cpio \
		rsync \
		xorg \
		expect \
		dos2unix \
		google-perftools \
		default-jre \
		locales

RUN useradd -m ci
RUN apt-get clean
COPY install_config.txt /tmp/install_config.txt
RUN mkdir /root/.Xilinx
COPY wi_authentication_key /root/.Xilinx/wi_authentication_key
RUN locale-gen en_US.UTF-8 
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 
COPY FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin /tmp/FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin

RUN 	mkdir /tmp/install \
	&& /tmp/FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin --target /tmp/install -- --agree XilinxEULA,3rdPartyEULA --batch Install --config /tmp/install_config.txt \
        && rm -rf /tools/Xilinx/Download \
	&& rm -rf /tools/Xilinx/.xinstall \
	&& rm -rf /tmp/install \
	&& rm -f /tmp/FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin
#RUN source /export/data_1/Xilinx/Vivado/2022.2/settings64.sh
#RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/export/data_1/Xilinx/Vivado/2022.2/lib/lnx64.o/

